### ISSUE TITLE
Error: No such file or directory 'ccs_single' in processMimic.py

### ISSUE THREAD

**Issue by ducnx** [jygao97/CAMP#1]
I downloaded and put the Single-level and Multi-level CCS file (download under section 'ASCII CCS Program Files for Use with SAS, STATA, or SPSS' from the link in README) in the `./data/ccs` folder. However, upon running `processMimic.py`, the script raise error: `No such file or directory: './data/ccs/ccs_single'`, at this [line](https://github.com/jygao97/CAMP/blob/baece7b34a637132a73e01c2bcd005f118bd45e2/processMimic.py#L8).
Can you please check whether I download the incorrect file, or your code has bug?

**Comment by jygao97** [comment]
Hi Ducnx,

I think first you download the incorrect file. You should download file under section 'CCS Information' for Appendix A and C (check my paper for correct link). Then you should rename the file to "ccs_multi"  and "ccs_single" as the code requires (you can also modify the filename in the code). Let me know if you still fail to run it.

Regards

**Comment by ducnx** [comment]
That resolves the error. I'm able to run the script.
However, there's a minor error at [line](https://github.com/jygao97/CAMP/blob/baece7b34a637132a73e01c2bcd005f118bd45e2/processMimic.py#L20), as `curCid` was not initialized. I initialize `curCid = 0` and the error disappears.
